---
title: "Analyze Environment"
author: "Jonathan Jupke"
date: "10 3 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_knit$set(root.dir = here::here())
```
<!-- SETUP -->
```{r setup2}
source("R/setup.R")
#library(MASS)
library(ggrepel)
```

```{r load data}
data_env = readRDS("data/taxa_env.rds")
data_exp = readRDS("data/taxa_exp.rds")
data_exp$Season %<>% as.factor()
data_exp$Cat_Y %<>% as.factor()
contrasts(data_exp$Pond) = "contr.sum"
contrasts(data_exp$Season) = "contr.treatment"
contrasts(data_exp$Cat_Y) = "contr.treatment"
data = bind_cols(data_env, data_exp)
```

```{r echo = TRUE}
data_env_y1 = data_env[which(data_exp$Cat_Y == "1st"), ]
data_env_y2 = data_env[which(data_exp$Cat_Y == "2nd"), ]
data_env_mod = data_env
data_env_mod %<>% 
	+.1 %>%
	log10() %>%
	scale(scale=T,center=T) %>% 
	as.data.frame()
data_env_y1 %<>% 
	+.1 %>%
	log10() %>%
	scale(scale=T,center=T) %>% 
	as.data.frame()
data_env_y2 %<>% 
	+.1 %>%
	log10() %>%
	scale(scale=T,center=T) %>% 
	as.data.frame()

```

```{r, warn = FALSE}
mv_env    =  mvabund(data_env_mod)
mv_env_y1 =  mvabund(data_env_y1)
mv_env_y2 =  mvabund(data_env_y2)
```

```{r echo=TRUE}
fit_uo_ga    <- gllvm(y = mv_env, family = gaussian())
fit_uo_ga_y1 <- gllvm(y = mv_env_y1, family = gaussian())
fit_uo_ga_y2 <- gllvm(y = mv_env_y2, family = gaussian())
```

## Both years 
```{r}
plot(fit_uo_ga, which = 2)
```

```{r}
resids =
	residuals(fit_uo_ga) %>%
	.[[1]] %>%
	as.data.frame() %>%
	pivot_longer(cols = everything()) 
lin_pred = 
	residuals(fit_uo_ga) %>%
	.[[2]] %>%
	as.data.frame() %>%
	pivot_longer(cols = everything()) 

resids$lin_pred = lin_pred$value

resids %>% 
	ggplot(aes(x = lin_pred, y = value, col = name)) + 
	geom_point() + 
	geom_hline(yintercept = 0, lty = 2) + 
	geom_smooth(method = "lm", col = "black") + 
	facet_wrap(.~name, scales = "free") + 
	theme(panel.grid = element_blank(), 
	      legend.position = "none")

```


```{r}
residuals(fit_uo_ga) %>%
	.[[1]] %>% 
	as.data.frame() %>% 
	pivot_longer(cols = everything()) %>% 
	mutate(name = factor(name)) %>% 
	ggplot(aes(x = name, y = value, col = name)) + 
	geom_violin()+
	geom_point(, alpha = 0.3) + 
	geom_hline(yintercept = 0) + 
	theme(legend.position = "none")
```
What are the NH4 outliers? 
```{r}
out = as.data.frame(residuals(fit_uo_ga)[[1]])
out_nh4 = which(out$NH4 > 1.5)
data$nh4_out = FALSE
data$nh4_out[which(out$NH4 > 1.5)] = TRUE
data %>% 
	ggplot(aes(y = NH4, x = DaysFromBeg, col = nh4_out)) + 
	geom_point() + 
	facet_wrap(.~Pond)
```
What are the NO3 outliers? 
```{r}
out = as.data.frame(residuals(fit_uo_ga)[[1]])
data$no3_out = FALSE
data$no3_out[which(out$NO3 > 1)] = TRUE
data %>% 
	ggplot(aes(y = NO3, x = DaysFromBeg, col = no3_out, shape = Season)) + 
	geom_point() + 
	facet_wrap(.~Pond) + 
	theme(panel.grid = element_blank())
```
What are the Water level outliers? 
```{r}
out = as.data.frame(residuals(fit_uo_ga)[[1]])
data$wl_out = FALSE
data$wl_out[which(abs(out$WatLev) > 3)] = TRUE
data %>% 
	ggplot(aes(y = WatLev, x = DaysFromBeg, col = wl_out, shape = Season)) + 
	geom_point() + 
	facet_wrap(.~Pond) + 
	theme(panel.grid = element_blank())
```
```{r}
ordiplot.gllvm(fit_uo_ga, biplot = T, predict.region = T)
```
```{r}
env_var = fit_uo_ga$params$theta %>% 
	as.data.frame() %>% 
	mutate(para = rownames(fit_uo_ga$params$theta),
	       Season = "Parameters")
fit_uo_ga$lvs %>% 
	as.data.frame() %>% 
	bind_cols(data) %>% 
	ggplot(aes(x = LV1, y=LV2), size = 2) +
	geom_hline(yintercept = 0, lty = 2) + 
	geom_vline(xintercept = 0, lty = 2) + 
	geom_point(aes(fill = Cat_Y), size = 3, shape = 21) +
	geom_text_repel(data = env_var, aes(label = para)) + 
	facet_wrap(.~Season) +
	theme(panel.grid = element_blank()) 
```

## Year 1 

```{r}
plot(fit_uo_ga_y1, which = 2)
```

```{r}
resids =
	residuals(fit_uo_ga_y1) %>%
	.[[1]] %>%
	as.data.frame() %>%
	pivot_longer(cols = everything()) 
lin_pred = 
	residuals(fit_uo_ga_y1) %>%
	.[[2]] %>%
	as.data.frame() %>%
	pivot_longer(cols = everything()) 

resids$lin_pred = lin_pred$value

resids %>% 
	ggplot(aes(x = lin_pred, y = value, col = name)) + 
	geom_point() + 
	geom_hline(yintercept = 0, lty = 2) + 
	geom_smooth(method = "lm", col = "black") + 
	facet_wrap(.~name, scales = "free") + 
	theme(panel.grid = element_blank(), 
	      legend.position = "none")

```

```{r}
residuals(fit_uo_ga_y1) %>%
	.[[1]] %>% 
	as.data.frame() %>% 
	pivot_longer(cols = everything()) %>% 
	mutate(name = factor(name)) %>% 
	ggplot(aes(x = name, y = value, col = name)) + 
	#geom_violin()+
	geom_point(alpha =1) + 
	geom_hline(yintercept = 0) + 
	#stat_summary(geom = "point", fun = mean, col = "black", aes(group = name)) + 
	theme(legend.position = "none")
```

What are the PO4 outliers? 
```{r}
out = as.data.frame(residuals(fit_uo_ga_y1)[[1]])
datay1 = filter(data, Cat_Y == "1st")
datay1$po4_out = FALSE
datay1$po4_out[which(out$PO4 < -5)] = TRUE
datay1 %>% 
	ggplot(aes(y = PO4, x = DaysFromBeg, col = po4_out, shape = Season)) + 
	geom_point() + 
	facet_wrap(.~Pond) + 
	theme(panel.grid = element_blank())
```

```{r}
ordiplot.gllvm(fit_uo_ga_y1, biplot = T, predict.region = T)
```
```{r}
env_var = fit_uo_ga_y1$params$theta %>% 
	as.data.frame() %>% 
	mutate(para = rownames(fit_uo_ga_y1$params$theta),
	       Season = "Parameters")
fit_uo_ga_y1$lvs %>% 
	as.data.frame() %>% 
	bind_cols(filter(data, Cat_Y == "1st")) %>% 
	ggplot(aes(x = LV1, y=LV2), size = 2) +
	geom_hline(yintercept = 0, lty = 2) + 
	geom_vline(xintercept = 0, lty = 2) + 
	geom_point(aes(fill = Pond), size = 2, shape = 21) +
	geom_text_repel(data = env_var, aes(label = para)) + 
	facet_wrap(.~Season) +
	theme(panel.grid = element_blank()) 
```

## Year 2 

```{r}
plot(fit_uo_ga_y2, which = 2)
```

```{r}
resids =
	residuals(fit_uo_ga_y1) %>%
	.[[1]] %>%
	as.data.frame() %>%
	pivot_longer(cols = everything()) 
lin_pred = 
	residuals(fit_uo_ga_y1) %>%
	.[[2]] %>%
	as.data.frame() %>%
	pivot_longer(cols = everything()) 

resids$lin_pred = lin_pred$value

resids %>% 
	ggplot(aes(x = lin_pred, y = value, col = name)) + 
	geom_point() + 
	geom_hline(yintercept = 0, lty = 2) + 
	geom_smooth(method = "lm", col = "black") + 
	facet_wrap(.~name, scales = "free") + 
	theme(panel.grid = element_blank(), 
	      legend.position = "none")

```


```{r}
residuals(fit_uo_ga_y2) %>%
	.[[1]] %>% 
	as.data.frame() %>% 
	pivot_longer(cols = everything()) %>% 
	mutate(name = factor(name)) %>% 
	ggplot(aes(x = name, y = value, col = name)) + 
	#geom_violin()+
	geom_point(alpha = 1) + 
	geom_hline(yintercept = 0) + 
	theme(legend.position = "none")
```

What are the Conductivity outliers? 
```{r}
out = as.data.frame(residuals(fit_uo_ga_y2)[[1]])
datay2 = filter(data, Cat_Y == "2nd")
datay2$cond_out = FALSE
datay2$cond_out[which(out$Cond > 2)] = TRUE
datay2 %>% 
	ggplot(aes(y = Cond, x = DaysFromBeg, col = cond_out, shape = Season)) + 
	geom_point() + 
	facet_wrap(.~Pond) + 
	theme(panel.grid = element_blank())
```
What are the Sodium outliers? 
```{r}
out = as.data.frame(residuals(fit_uo_ga_y2)[[1]])
datay2 = filter(data, Cat_Y == "2nd")
datay2$cond_out = FALSE
datay2$cond_out[which(out$Na < -3)] = TRUE
datay2 %>% 
	ggplot(aes(y = Na, x = DaysFromBeg, col = cond_out, shape = Season)) + 
	geom_point() + 
	facet_wrap(.~Pond) + 
	theme(panel.grid = element_blank())
```
What are the Oxygen outliers? 
```{r}
out = as.data.frame(residuals(fit_uo_ga_y2)[[1]])
datay2 = filter(data, Cat_Y == "2nd")
datay2$cond_out = FALSE
datay2$cond_out[which(out$O2 < -2)] = TRUE
datay2 %>% 
	ggplot(aes(y = O2, x = DaysFromBeg, col = cond_out, shape = Season)) + 
	geom_point() + 
	facet_wrap(.~Pond) + 
	theme(panel.grid = element_blank())
```

```{r}
ordiplot.gllvm(fit_uo_ga_y2, biplot = T, predict.region = T)
```
```{r}
env_var = fit_uo_ga_y2$params$theta %>% 
	as.data.frame() %>% 
	mutate(para = rownames(fit_uo_ga_y2$params$theta),
	       Season = "Parameters")
fit_uo_ga_y2$lvs %>% 
	as.data.frame() %>% 
	bind_cols(filter(data, Cat_Y == "2nd")) %>% 
	ggplot(aes(x = LV1, y=LV2), size = 2) +
	geom_hline(yintercept = 0, lty = 2) + 
	geom_vline(xintercept = 0, lty = 2) + 
	geom_point(aes(fill = Pond), shape = 21, size = 2) +
	geom_text_repel(data = env_var, aes(label = para)) + 
	facet_wrap(.~Season) +
	theme(panel.grid = element_blank()) 
```


## Constrained ordination


```{r}
#data_env = data_env[,-11]
```


```{r fit co exp, echo = T}
# both years 
fit_co = gllvm(y = data_env_mod,
                  X = data_exp,
                  formula = ~ Pond + Season + Cat_Y*DaysFromBeg,
                  family = "gaussian",
                  num.lv = 2)
# year 1 
fit_co_y1 = gllvm(y = data_env_y1,
                  X = filter(data_exp, Cat_Y == "1st"),
                  formula = ~ Pond + Season + DaysFromBeg,
                  family = "gaussian",
                  num.lv = 2)
# year 2  
fit_co_y2 = gllvm(y = data_env_y2,
                  X = filter(data_exp, Cat_Y == "2nd"),
                  formula = ~ Pond + Season + DaysFromBeg,
                  family = "gaussian",
                  num.lv = 2)

```

## Both Years 

```{r}
plot(fit_co, which = 2)
```
```{r}
coef_plot = fit_co$params$Xcoef
#summary(fit_co)


ziel = fit_co$params$Xcoef
sig = as.data.frame(confint(fit_co))
names(sig) = c("lb", "ub")
sig %<>%
	mutate(sig1 = lb<0,
	       sig2 = ub<0,
	       params = rownames(sig)) %>%
	mutate(sig3 = sig1 == sig2) %>% 
	mutate(mult = ifelse(sig3,1,0)) %>% 
	dplyr::select(!c("sig1", "sig2", "ub", "lb", "sig3")) %>%
	filter(str_detect(params, "Xcoef", negate = F)) %>% 
	mutate(pond = str_extract(params, "Pond[0-9]+"), 
	       variable = str_remove(str_extract(params, "\\:.*"), "\\:"),
	       season = str_remove(str_extract(params, "Season.*\\:"), "\\:"),
	       year = str_remove(str_extract(params, "Cat.*\\:"), "\\:"),
	       day = str_remove(str_extract(params, "Day.*\\:"), "\\:")
	       	) %>% 
	mutate(predictor = ifelse(!is.na(pond), pond, ifelse(!is.na(season), season,NA))) %>% 
	dplyr::select(!c("pond", "season"))

for (i in 1:nrow(sig)){
	if (!is.na(sig$predictor[i])) next()
	if (is.na(sig$year[i]) & !is.na(sig$day[i]))
		sig$predictor[i] = sig$day[i]
	if (!is.na(sig$year[i]) & is.na(sig$day[i]))
		sig$predictor[i] = sig$year[i]
	if (!is.na(sig$year[i]) & !is.na(sig$day[i])){
		sig$predictor[i] = "Cat_Y2nd:DaysFromBeg"
		sig$variable[i] = str_remove(sig$variable[i], "DaysFromBeg:")
	}
		
}

sig %<>% dplyr::select(!c("params", "year","day"))

sig %<>% 
	pivot_wider(id_cols = "variable",
	            names_from = "predictor",
	            values_from = "mult")  
sig %<>% column_to_rownames("variable")

ziel2 = sig * ziel

colort = colorRampPalette(c("blue", "white", "red"))
#a      = max(abs(ziel2))
a = 3.5
coef_plot = levelplot((as.matrix(ziel2)),
                                col.regions = colort(100), cex.lab =1.3,
                               at = seq(-a, a, length = 100), scales = list(x = list(rot = 45)))
coef_plot
```
## Year 1 

```{r}
plot(fit_co_y1)
```
```{r}
ordiplot.gllvm(fit_co_y1, biplot = T)
```

```{r}
ziel = fit_co_y1$params$Xcoef
sig = as.data.frame(confint(fit_co_y1))
names(sig) = c("lb", "ub")
sig %<>%
	mutate(sig1 = lb<0,
	       sig2 = ub<0,
	       params = rownames(sig)) %>%
	mutate(sig3 = sig1 == sig2) %>% 
	mutate(mult = ifelse(sig3,1,0)) %>% 
	dplyr::select(!c("sig1", "sig2", "ub", "lb", "sig3")) %>%
	filter(str_detect(params, "Xcoef", negate = F)) %>% 
	mutate(pond = str_extract(params, "Pond[0-9]+"), 
	       variable = str_remove(str_extract(params, "\\:.*"), "\\:"),
	       season = str_remove(str_extract(params, "Season.*\\:"), "\\:"),
	       year = str_remove(str_extract(params, "Cat.*\\:"), "\\:"),
	       day = str_remove(str_extract(params, "Day.*\\:"), "\\:")
	       	) %>% 
	mutate(predictor = ifelse(!is.na(pond), pond, ifelse(!is.na(season), season,NA))) %>% 
	dplyr::select(!c("pond", "season"))

for (i in 1:nrow(sig)){
	if (!is.na(sig$predictor[i])) next()
	if (is.na(sig$year[i]) & !is.na(sig$day[i]))
		sig$predictor[i] = sig$day[i]
	if (!is.na(sig$year[i]) & is.na(sig$day[i]))
		sig$predictor[i] = sig$year[i]
	if (!is.na(sig$year[i]) & !is.na(sig$day[i])){
		sig$predictor[i] = "Cat_Y2nd:DaysFromBeg"
		sig$variable[i] = str_remove(sig$variable[i], "DaysFromBeg:")
	}
		
}

sig %<>% dplyr::select(!c("params", "year","day"))

sig %<>% 
	pivot_wider(id_cols = "variable",
	            names_from = "predictor",
	            values_from = "mult")  
sig %<>% column_to_rownames("variable")

ziel2 = sig * ziel

colort = colorRampPalette(c("blue", "white", "red"))
#a      = max(abs(ziel2))
a= 3.5
coef_plot = levelplot((as.matrix(ziel2)),
                                col.regions = colort(100), cex.lab =1.3,
                               at = seq(-a, a, length = 100), scales = list(x = list(rot = 45)))
coef_plot
```

## Year 2 

```{r}
plot(fit_co_y2)
```

```{r}
ziel = fit_co_y2$params$Xcoef
sig = as.data.frame(confint(fit_co_y2))
names(sig) = c("lb", "ub")
sig %<>%
	mutate(sig1 = lb<0,
	       sig2 = ub<0,
	       params = rownames(sig)) %>%
	mutate(sig3 = sig1 == sig2) %>% 
	mutate(mult = ifelse(sig3,1,0)) %>% 
	dplyr::select(!c("sig1", "sig2", "ub", "lb", "sig3")) %>%
	filter(str_detect(params, "Xcoef", negate = F)) %>% 
	mutate(pond = str_extract(params, "Pond[0-9]+"), 
	       variable = str_remove(str_extract(params, "\\:.*"), "\\:"),
	       season = str_remove(str_extract(params, "Season.*\\:"), "\\:"),
	       year = str_remove(str_extract(params, "Cat.*\\:"), "\\:"),
	       day = str_remove(str_extract(params, "Day.*\\:"), "\\:")
	       	) %>% 
	mutate(predictor = ifelse(!is.na(pond), pond, ifelse(!is.na(season), season,NA))) %>% 
	dplyr::select(!c("pond", "season"))

for (i in 1:nrow(sig)){
	if (!is.na(sig$predictor[i])) next()
	if (is.na(sig$year[i]) & !is.na(sig$day[i]))
		sig$predictor[i] = sig$day[i]
	if (!is.na(sig$year[i]) & is.na(sig$day[i]))
		sig$predictor[i] = sig$year[i]
	if (!is.na(sig$year[i]) & !is.na(sig$day[i])){
		sig$predictor[i] = "Cat_Y2nd:DaysFromBeg"
		sig$variable[i] = str_remove(sig$variable[i], "DaysFromBeg:")
	}
		
}

sig %<>% dplyr::select(!c("params", "year","day"))

sig %<>% 
	pivot_wider(id_cols = "variable",
	            names_from = "predictor",
	            values_from = "mult")  
sig %<>% column_to_rownames("variable")

ziel2 = sig * ziel

colort = colorRampPalette(c("blue", "white", "red"))
#a      = max(abs(ziel2))
a = 3.5
coef_plot = levelplot((as.matrix(ziel2)),
                                col.regions = colort(100), cex.lab =1.3,
                               at = seq(-a, a, length = 100), scales = list(x = list(rot = 45)))
coef_plot
```