---
title: "environmental turnover"
author: "Jonathan Jupke"
date: "17.3.2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_knit$set(root.dir = here::here())
library(knitr)
library(kableExtra)
```

```{r setup2, echo = F}
source("R/setup.R")
source("R/fun_coef_plot.R")
```

```{r load data}
data_env = readRDS("data/taxa_env.rds")
data_exp = readRDS("data/taxa_exp.rds")
```

```{r prepare season data, echo = FALSE}
data_exp %<>% 
	mutate(season_year = paste0(Season, str_extract(Cat_Y, "[0-9]")))

data_exp$season_year %<>% factor(levels = c("Win1","Spr1", "Sum1",  "Win2","Spr2", "Sum2" ))
# complete ponds 
#data_exp$Pond %>% table
keep_pond = which(data_exp$Pond %in% paste0("P", c(1,2,4,5,6,7,8,9)))

```

Subset to complete ponds. 
```{r subset complete}
data_exp = data_exp[keep_pond, ]
data_env  = data_env[keep_pond, ]
data_env = scale(data_env)
```


## Stepwise turnover 
```{r warn = FALSE}

out = expand.grid(pond = paste0("P", 1:12),
                  season = 1:5,
                  distance = 666)
setDT(out)
# loop over ponds 
for (i in 1:uniqueN(data_exp$Pond)) {
	for (j in seq_along(levels(data_exp$season_year))) {
		if (j == length(levels(data_exp$season_year)))
			next()
		id1 = which(data_exp$season_year == levels(
			data_exp$season_year)[j] &
			data_exp$Pond == paste0("P", i))
		id2 = which(data_exp$season_year == levels(
			data_exp$season_year)[j + 1] &
			data_exp$Pond == paste0("P", i))
		
		if (length(id1) == 0 | length(id2) == 0)
			next()
		
		if ("matrix" %in% class(data_env[id1, ])){
			d1 = data_env[id1, ] %>% apply(2, mean)	
		} else {
			d1 = data_env[id1, ]	
		}
		if ("matrix" %in% class(data_env[id2, ])){
			d2 = data_env[id2, ] %>% apply(2, mean)	
		} else {
			d2 = data_env[id2, ]	
		}
		# d1 = data_env[id1, ] %>% apply(2, mean)
		# d2 = data_env[id2, ] %>% apply(2, mean)
		d3 = bind_rows(d1, d2)
		d4 = vegan::vegdist(d3, method = "euclidean")
		out[season == j & pond == paste0("P", i), distance := d4]
		
	}
	
	
	
}
out %<>% 
	mutate(season = replace(season, season == 1, "WiSp1")) %>% 
	mutate(season = replace(season, season == 2, "SpSu1")) %>% 
	mutate(season = replace(season, season == 3, "SuWi1")) %>% 
	mutate(season = replace(season, season == 4, "WiSp2")) %>% 
	mutate(season = replace(season, season == 5, "SpSu2")) %>% 
	mutate(season = factor(season, levels = c("WiSp1", "SpSu1", "SuWi1", "WiSp2", "SpSu2")))

out_summary = out[distance != 666, mean(distance), by = season]


plot = ggplot(data = filter(out,
	 distance != 666),
       aes(
       	x = season,
       	y = distance
       )) +
	geom_line (alpha = 0.7,  aes(col = pond, group = pond)) +
	geom_point(alpha = 0.3,size = 2, aes(col = pond, group = pond)) +
	stat_summary(geom="point",
	             fun = mean,
	             size = 2) + 
	stat_summary(geom = "line",
	             fun = mean,
	             group = 1,
	             size = 2) + 
	theme(panel.grid = element_blank())
#	geom_point(data = out_summary, aes(x = season, y = V1), size = 2) 
	#geom_line(aes(group = season))
	


```

## Cummulative change. 
```{r warn = FALSE, echo = FALSE}

out = expand.grid(pond = paste0("P", 1:12),
                  season = 1:5,
                  distance = 666)
setDT(out)
# loop over ponds 
for (i in 1:uniqueN(data_exp$Pond)) {
	for (j in seq_along(levels(data_exp$season_year))) {
		if (j == length(levels(data_exp$season_year)))
			next()
		id1 = which(data_exp$season_year == levels(
			data_exp$season_year)[1] &
			data_exp$Pond == paste0("P", i))
		id2 = which(data_exp$season_year == levels(
			data_exp$season_year)[j + 1] &
			data_exp$Pond == paste0("P", i))
		
		if (length(id1) == 0 | length(id2) == 0)
			next()
		
		if ("matrix" %in% class(data_env[id1, ])){
			d1 = data_env[id1, ] %>% apply(2, mean)	
		} else {
			d1 = data_env[id1, ]	
		}
		if ("matrix" %in% class(data_env[id2, ])){
			d2 = data_env[id2, ] %>% apply(2, mean)	
		} else {
			d2 = data_env[id2, ]	
		}
		# d1 = data_env[id1, ] %>% apply(2, mean)
		# d2 = data_env[id2, ] %>% apply(2, mean)
		d3 = bind_rows(d1, d2)
		d4 = vegan::vegdist(d3, method = "euclidean")
		out[season == j & pond == paste0("P", i), distance := d4]
		
	}
	
	
	
}
out %<>% 
	mutate(season = replace(season, season == 1, "Spring1")) %>% 
	mutate(season = replace(season, season == 2, "Summer1")) %>% 
	mutate(season = replace(season, season == 3, "Winter2")) %>% 
	mutate(season = replace(season, season == 4, "Spring2")) %>% 
	mutate(season = replace(season, season == 5, "Summer2")) %>% 
	mutate(season = factor(season, levels = c("Spring1", "Summer1", "Winter2", "Spring2", "Summer2")))

plot = ggplot(data = filter(out,
	 distance != 666),
       aes(x = season,
           y = distance)) +
	geom_point(alpha = 0.3, size = 2, aes(col = pond, group = pond)) +
	geom_line (alpha = 0.7,  aes(col = pond, group = pond)) +
	stat_summary(geom = "point",
	             fun = mean, size = 2) +
	stat_summary(
		geom = "line",
		fun = mean,
		size = 2,
		group = 1
	)
```

## Differences among ponds. 

```{r echo = F}
sv_list = list()


for (i in seq_along(levels(data_exp$season_year))) {
	
	id1 = which(data_exp$season_year == levels(data_exp$season_year)[i])
	if (length(id1) == 0){
		next()	
	}
	d1 = data_env[id1,] %>% data.frame() %>% setDT
	d1$pond = data_exp[id1, "Pond"]
	# aggregate observation in ponds 
	d1 = d1[, lapply(.SD, mean), by = pond]
	# remove empty ponds 
	if (any(rowSums(d1[,-1]) == 0)){
		zrid = which(rowSums(d1[,-1]) == 0)
		d1 = d1[-zrid,]
	}
	d2 = vegan::vegdist(d1[,-1], method = "euclidean")
	d3 = as.matrix(d2)
	d3[upper.tri(d3)] = 0
	colnames(d3) = as.character(d1$pond)
	rownames(d3) = as.character(d1$pond)
	
	d4 = as.data.frame(d3)
	
	d4$pond = rownames(d4)
	d4 %<>% 
		pivot_longer(cols = !pond, 
		             names_to = "pond2",
		             values_to = "distance")
	d4$season = levels(data_exp$season_year)[i]
	d4 %<>% filter(pond != pond2) %>% 
		filter(distance != 0)
	sv_list[[i]] = d4
}# END i 

out = rbindlist(sv_list)
out$season = factor(out$season, levels = c("Win1", "Spr1", "Sum1", "Win2", "Spr2", "Sum2"))
out %<>%
	mutate(num1 = str_remove(pond, "P"),
	       num2 = str_remove(pond2, "P")) %>% 
	mutate(onefirst = num1<num2) %>% 
	mutate(pond3 = case_when(onefirst ~ paste0(pond, pond2), 
		     !onefirst ~ paste0(pond2,pond)
		     )) %>% 
	mutate(pond3 = factor(pond3))

plot = 
	out %>% 
	ggplot(aes(x = season,
	           y = distance, 
	           col = pond3,
	           group = pond3)) + 
	geom_point(alpha = 0.3) + 
	geom_line(alpha = .3) + 
	stat_summary(geom = "point",
	             fun = mean,
	             col = "black",
	             group = 1,
	             size = 2) + 
	stat_summary(geom = "line",
	             fun = mean,
	             col = "black", 
	             group = 1,
	             size = 2) +
	theme(#legend.position = "none", 
	      panel.grid = element_blank())
```

## Differences among ponds aggregated 

## Differences among ponds. 

```{r echo = F}
sv_list = list()


for (i in seq_along(levels(data_exp$season_year))) {
	
	id1 = which(data_exp$season_year == levels(data_exp$season_year)[i])
	if (length(id1) == 0){
		next()	
	}
	d1 = data_env[id1,] %>% data.frame() %>% setDT
	d1$pond = data_exp[id1, "Pond"]
	# aggregate observation in ponds 
	d1 = d1[, lapply(.SD, mean), by = pond]
	# remove empty ponds 
	if (any(rowSums(d1[,-1]) == 0)){
		zrid = which(rowSums(d1[,-1]) == 0)
		d1 = d1[-zrid,]
	}
	d2 = vegan::vegdist(d1[,-1], method = "euclidean")
	d3 = as.matrix(d2)
	d3[upper.tri(d3)] = 0
	colnames(d3) = as.character(d1$pond)
	rownames(d3) = as.character(d1$pond)
	
	d4 = as.data.frame(d3)
	
	d4$pond = rownames(d4)
	d4 %<>% 
		pivot_longer(cols = !pond, 
		             names_to = "pond2",
		             values_to = "distance")
	d4$season = levels(data_exp$season_year)[i]
	d4 %<>% filter(pond != pond2) %>% 
		filter(distance != 0)
	sv_list[[i]] = d4
}# END i 

out = rbindlist(sv_list)
out$season = factor(out$season, levels = c("Win1", "Spr1", "Sum1", "Win2", "Spr2", "Sum2"))
out %<>%
	mutate(num1 = str_remove(pond, "P"),
	       num2 = str_remove(pond2, "P")) %>% 
	mutate(onefirst = num1<num2) %>% 
	mutate(pond3 = case_when(onefirst ~ paste0(pond, pond2), 
		     !onefirst ~ paste0(pond2,pond)
		     )) %>% 
	mutate(pond3 = factor(pond3))

out1 = out[,c("pond", "distance", "season")]
out2 = out[,c("pond2", "distance", "season")]
names(out2)[1] = "pond"

plot = out1 %>% 
	bind_rows(out2) %>% 
	mutate(pond = factor(pond)) %>% 
	ggplot(aes(x = season, y = distance, col = pond)) + 
	stat_summary(fun = mean, geom = "point") + 
	stat_summary(fun = mean, geom = "line", aes(group = pond), alpha = 0.4) + 
	stat_summary(fun = mean, geom = "point", group = aes(season), col = "black", size = 2)+
	stat_summary(fun = mean, geom = "line", group = 1 ,col = "black", size = 2)
	


```
